### ISSUE TITLE
detect likely misspellings in boolean expressions

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-validate#106]
If a user enters 'yes' in XLSForm for required (and perhaps constraint, and relevant, and readonly), it's transformed into `true()` in the XForm.

However, if the user makes a spelling mistake and writes 'ues', this just gets copied. E.g. `ues and ../a > 5` becomes `required="ues and ../a > 5"`. This is not an XPath syntax error, but clearly **childnode** `<ues>` cannot exist in ODK world (except for relevant expressions).

It would be nice if we could detect this (nodes without slashes) and prompt an error or warning.

Note, it is possible that our evaluator chokes on the above expression unless `ues` is inside brackets `(ues)`. That would be different issue and should be reported at https://github.com/enketo/openrosa-xpath-evaluator/issues.

**Comment by MartijnR** [comment]
an easy check to add would be for values that are alphanumeric strings (without other characters other than _, and without spaces). regex :`/^[A-z0-9_]+$/`

**Comment by MartijnR** [comment]
* [ ] check what pyxform returns exactly for e.g. "ues" and "w6"

**Comment by pbowen-oc** [comment]
@MartijnR - Were these checks added as warnings (not errors)?

**Comment by MartijnR** [comment]
yes, they were
