### ISSUE TITLE
Unable to install puppeteer 19.7.2

### ISSUE THREAD

**Issue by svadla-oc** [enketo/enketo-validate#125]
Latest version of enketo-validate is using puppeteer v19.7.2. While running this latest version, we are encountering the below error. It seems like this error is related to this bug https://github.com/puppeteer/puppeteer/issues/9533, however, that bug was fixed in v19.6.1.

> Error: Could not find Chromium (rev. 1095492). This can occur if either
>  1. you did not perform an installation before running the script (e.g. `npm install`) or
>  2. your cache path is incorrectly configured (which is: /home/java_svc/.cache/puppeteer).
> For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.

**Comment by MartijnR** [comment]
I just tried a clean install (after `rm -R node_modules`) and it worked for me on a Mac.

**Comment by svadla-oc** [comment]
Thanks @MartijnR for looking into this. It turns out that the issue was happening because we are using one user to install the modules and a different user for running the application. Because of this, puppeteer was installing chromium in one directory and expecting it in a different directory while running the application. Per puppeteer's documentation (referenced below), starting with v19.0.0, the location of chromium installation has been changed to user's home directory. 

> When you install Puppeteer, it automatically downloads a recent version of Chromium (~170MB macOS, ~282MB Linux, ~280MB Windows) that is [guaranteed to work](https://pptr.dev/faq#q-why-doesnt-puppeteer-vxxx-work-with-chromium-vyyy) with Puppeteer. The browser is downloaded to the $HOME/.cache/puppeteer folder by default (starting with Puppeteer v19.0.0).

**Comment by korablin** [comment]
@svadla-oc I am still hitting issue when running puppeteer in google cloud functions

**Comment by bdineshvarma** [comment]
@svadla-oc This issue is still there for version `19.7.5`
