### ISSUE TITLE
executable?

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-validate#2]
explore https://github.com/nexe/nexe

Seems rather cool. Won't require installation of nodeJS.

**Comment by MartijnR** [comment]
probably no longer feasible now that we've added libxslt (native module)

**Comment by lindsay-stevens** [comment]
I had some success with `pkg` https://github.com/zeit/pkg, which can bundle up enketo-validate with it's dependencies and a copy of nodejs - like magic :tada:

Hitches are:

- the compiled exe is a bit big (~40MB) 
- have to compile libxslt / libxmljs-mt on the target platform, which means platform-specific releases
- the compiled libxslt / libxmljs-mt have to be distributed alongside the exe but not inside it
- the compiled libxslt / libxmljs-mt are a bit big (~60MB)

On the bright side, it all zips down to ~30MB together. 

Below is how I finally managed to get it working (I think) on linux and windows. If this seems like something you'd want to use, it can probably be orchestrated via Travis / AppVeyor.

## linux
- Need some setup to compile, as per: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
  - Installs nodejs v9 plus the various build tools
- Install the packaging library: `npm install -g pkg`
- In the project root (where `package.json` is), build / install enketo-validate: `npm install`
- Run a `pkg` build for linux, specifying the entry point file: `pkg validate --targets node9-linux-x64`
- Copy main compiled file somewhere:
  - `mkdir -p ../packed`
  - `cp ./validate-linux ../packed/validate-linux`
- Copy the compiled libxmljs-mt files:
  - `mkdir -p ../packed/node_modules/libxmljs-mt/build/Release`
  - `cp -r node_modules/libxmljs-mt/build/Release ../packed/node_modules/libxmljs-mt/build/Release`
- Copy the compiled libxslt files:
  - `mkdir -p ../packed/node_modules/libxslt/build/Release`
  - `cp -r node_modules/libxslt/build/Release ../packed/node_modules/libxslt/build/Release`
- Hopefully it works: `../packed/validate-linux --me`


## windows
- Need some setup to compile, as per: https://github.com/nodejs/node-gyp#on-windows
  - Install VS2015 build tools: http://landinghub.visualstudio.com/visual-cpp-build-tools
  - set npm config: `npm config set msvs_version 2015`
  - Install python 2.7
  - set npm config: `npm config set python /path/to/executable/python2.7`
- Install the packaging library: `npm install -g pkg`
- In the project root (where `package.json` is), build / install enketo-validate: `npm install`
- Run a `pkg` build for linux, specifying the entry point file: `pkg validate --targets node9-win-x64`
- Copy main compiled file somewhere:
  - `mkdir -p ../packed`
  - `cp .\validate.exe ..\packed\validate.exe`
- Copy the compiled libxmljs-mt files:
  - `mkdir -p ..\packed\node_modules\libxmljs-mt\build\Release`
  - `cp -r node_modules\libxmljs-mt\build/Release ..\packed\node_modules\libxmljs-mt\build\Release`
- Copy the compiled libxslt files:
  - `mkdir -p ..\packed\node_modules\libxslt\build\Release`
  - `cp -r node_modules\libxslt\build\Release ..\packed\node_modules\libxslt\build\Release`
- Hopefully it works: `..\packed\validate.exe --me`

**Comment by MartijnR** [comment]
Wow. That's awesome. I wonder how portable the binaries are, e.g. between different versions of Linux. Will explore this!

Will also look into removing the `libxslt` dependency. That would make this more attractive. It's a very heavyweight solution for this purpose actually (though robust).

**Comment by MartijnR** [comment]
Just to let you know I'm working on creating the binaries for the release of 1.0.3. I should have them shortly. It's been a bit tedious, but hopefully that will not be the case in the future ;)

I am thinking a zip file with a structure like this:

linux
  -validate-linux
  -validate-linux-oc
  -node_modules
macos
  -validate-macos
  -node_modules
windows
  -validate.exe
  -node_modules

How does that sound to you @lindsay-stevens? Would you prefer 3 different assets to only download the one you need?

**Comment by lindsay-stevens** [comment]
Looks good to me - let me know if I can do anything to help. 

By the way I was wondering how it is that `pkg` does it's magic and found this helpful comment / comparison with other tools: https://github.com/zeit/pkg/issues/49#issuecomment-299374354

**Comment by MartijnR** [comment]
Thanks for that. 

It's released. https://api.github.com/repos/enketo/enketo-validate/releases/latest.

I add one big zip file as well as the 3 smaller os-specific ones. The latter is probably better for the future. Let me know if the filenames, folder names, zipfile names should change. Will create another issue to automate this.

Thanks for figuring this out! It's really cool once automated builds are sorted out.

**Comment by lindsay-stevens** [comment]
Awesome! Yes I think 3 separate assets would be easier to use, so I can write a pyxform download function to get the right one based on the host OS.

To smoke test portability successfully ran your builds in the following environments, using both the "--me" flag as well as actual XForms (the `xlsform_spec_test.xml` and `pull_data.xml` fixtures from pyxform):

- Linux on Ubuntu 16.04 WSL environment
- Windows build on Windows 10 environment
- Windows build on fresh Windows 10 VM (in case of some system dependency or something, in particular it doesn't have node installed)

Also from some trial and error it seems that the minimal files required for the executable (Windows and Linux) to function are the compiled exe and the *.node files, as follows:

```
│   validate.exe
│
└───node_modules
    ├───libxmljs-mt
    │   └───build
    │           xmljs.node
    │
    └───libxslt
        └───build
                node-libxslt.node
```

This brings the zip file sizes down to ~14MB for Windows and ~17MB for Linux.

Lastly - what is the difference between the `validate-linux` and `validate-linux-oc` builds? If a user on Linux wants to use enketo-validate, which one should they get (or how to choose)?

**Comment by MartijnR** [comment]
Ah great. I'll remove the other files. Thanks!

The -oc build is using OpenClinica's customized XPath evaluator. I'm trying to avoid OC having to fork enketo-validate or pyxform. However, I don't know what is the best way too deal with it on the pyxform side. Basically what you'd want for the OC installer is to remove `validate-linux` and rename `validate-linux-oc` to `validate-linux`. Maybe as a separate pyxform post-installation step?

It would be preferable for other users if the -oc build was in its own zip file perhaps, but I thought that might make the post-installation step more difficult.

If you prefer tar.gz files, also just let me know (it's probably slightly easier to create, at least for linux/macos builds).

**Comment by lindsay-stevens** [comment]
Using tar.gz for linux/macos is OK. I'm working on a fetch / update script that can be used as needed, like:

```bash
pip install pyxform
python validators/update.py --enketo_validate
```

So it could have an extra option flag to get the OC build (on linux only?)

```
python update.py --enketo_validate --oc
```

It's possible to do command subgroups with argparse so it could instead be available in the main CLI like so:

```
xls2xform update --enketo_validate --oc
```

**Comment by MartijnR** [comment]
I think it may not be so welcomed to add custom oc features to pyxform. I would keep anything oc-related out if possible. For enketo-validate it's a bit different because it's our own project (and OC created it).

**Comment by lindsay-stevens** [comment]
I think I found a way to make it work without hard-coding anything OC-related, see: https://github.com/XLSForm/pyxform/pull/171.

In this case, the user specifies the asset file name that they want to grab. It just requires that the `validate-linux-oc` and `validate-linux` builds have the exact same archive / zip file structure.

**Comment by MartijnR** [comment]
Very cool. Let me split he linux binaries into 2. I'll update the 1.0.3. release with that.

**Comment by MartijnR** [comment]
@lindsay-stevens, if there is a particular filename required, please specify the structure you need. I'm thinking `validate`, `validate`, `validate`, `validate.exe` might be easiest for the 4 executables, or not?

linux.zip
 - validate-linux or validate?
 - node_modules

linux-oc.zip
 - validate-linux-oc or validate?
 - node_modules

windows.zip
 - validate.exe
 - node_modules

macos.zip
 - validate-macos or validate?
 - node_modules

**Comment by lindsay-stevens** [comment]
The option of linux: `validate`, linux-oc: `validate`, windows: `validate.exe`, macos: `validate` would be ideal - that way I don't need to rename or detect anything on the pyxform side to invoke enketo-validate. Thanks!

**Comment by MartijnR** [comment]
Thanks. I've updated the latest release with this.
