### ISSUE TITLE
add warning for duplicate nodenames

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-validate#40]
strictly speaking it's allowed, but better to not do (for data exports)

**Comment by gushil** [comment]
@MartijnR Could you please attach xml form that have this issue in this thread? That would be very helpful. Thanks.

**Comment by MartijnR** [comment]
Sure!  

XLSForm: https://docs.google.com/spreadsheets/d/12cN6ol1yzoOuBKPWISDyDsRVLEzrlP9BSCX8CZD21so/edit#gid=0

XForm: 
[data.xml.txt](https://github.com/enketo/enketo-validate/files/3570853/data.xml.txt)

I actually thought that pyxform wouldn't allow this, but it does!
