### ISSUE TITLE
FormControl label validation running for setvalue elements

### ISSUE THREAD

**Issue by Pete-Fowles** [enketo/enketo-validate#64]
Hi Martijn

It seems that the validator is treating <setvalue event="..." ref="..."> elements in the body as formcontrols when validating labels.
I think the issue was introduced in this commit
https://github.com/enketo/enketo-validate/commit/b96b8a60ee0b5f77c20f4315aee7cfb9d7354229
in this formControl queries in this file src/xform.js 

You can see a failed test case showing this behaviour by using the setvalue.xml test form in the enketo-transformer library.

Kind Regards
Pete

**Comment by MartijnR** [comment]
Thank you Pete! Will fix this shortly.
