### ISSUE TITLE
check: error for XLSForm form with field-list on repeat?

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-validate#66]

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/1RsOXoiJFKj_RpYVdAKwEnkV5WE7RMGNs87rZoSkB9bA/edit?usp=sharing

**Comment by MartijnR** [comment]
It's actually not an error but a warning:

<img width="714" alt="Screen Shot 2020-05-21 at 4 18 02 PM" src="https://user-images.githubusercontent.com/627350/82611860-bc909d00-9b7e-11ea-80ee-cedc559af746.png">

@pbowen-oc, I wonder if OC is outputting warnings as errors.

Nonetheless, this should be neither:

* [ ] fix warning for field-list on repeat

**Comment by MartijnR** [comment]
Ah, actually I didn't test properly. It's an error in OpenClinica mode and a warning in regular mode.

**Comment by MartijnR** [comment]
I found this comment in the code:
```
 // OpenClinica would like all appearance warnings to be output as errors, for now
xform.checkAppearances( errors, errors );
```

So, I'll hold off on changing that until you confirm @pbowen-oc

**Comment by pbowen-oc** [comment]
@MartijnR - Yes, please have these output as warnings. I don't recall the reason for the previous request, but it doesn't seem to be what we want now.

**Comment by pbowen-oc** [comment]
@MartijnR - Should this one be a warning at all, though? We don't want to confuse our users with warnings for things they don't have any control of. Since we do want to show warnings for deprecated appearances they have specified, having warnings for things they can't control will seem to only add confusion.

**Comment by MartijnR** [comment]
> @MartijnR - Should this one be a warning at all, though? 

No, it was a general question that didn't really belong here.
