### ISSUE TITLE
Issue with nodenames starting with an underscore

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-validate#77]
`SyntaxError: 'data>allergies>_thead>note1' is not a valid selector`

See 'Form upload issue' email by @pbowen-oc on 07/17/2020.

[Allergies.pab.min.underscore.xml.txt](https://github.com/enketo/enketo-validate/files/4938494/Allergies.pab.min.underscore.xml.txt)

**Comment by MartijnR** [comment]
Looks like a bug in JSDOM

**Comment by MartijnR** [comment]
remaining:

* [ ] failing test comment-status in non-oc mode
* [ ] refactor using async/await
* [ ] remove JSDOM entirely (also for XML structure checks?)

**Comment by pbowen-oc** [comment]
@MartijnR - We're seeing the same syntax error in this case as before.

**Comment by MartijnR** [comment]
But not here, right? https://validate.enketo.org/oc/

**Comment by MartijnR** [comment]
Just in case, this is the command to check for any globally install npm packages (maybe an old enketo-validate version):

```
npm list -g --depth 0
```

This should not list enketo-validate because you've started installing it from git locally instead now I believe)

**Comment by pbowen-oc** [comment]
@MartijnR - We have an old version installed, so I'll retest once we update it.

**Comment by pbowen-oc** [comment]
Looks good in testing.
