### ISSUE TITLE
Error with trigger referencing date item in repeating group

### ISSUE THREAD

**Issue by pbowen-oc** [enketo/enketo-validate#87]
The following form produces these validation errors:
Found setvalue for "bp_dt_ymd " that does not exist in the model. 
Found setvalue for "bp_dt_ym " that does not exist in the model. 
Found setvalue for "bp_dt_y " that does not exist in the model.

[set value test.zip](https://github.com/enketo/enketo-validate/files/5405226/set.value.test.zip)

This is from a larger form that used other triggers that did not produce errors.

**Comment by MartijnR** [comment]
This turned out to be quite big issue. We can fix it in Enketo (adding relative `ref` support - big project) or in pyxform. Tbd.

**Comment by pbowen-oc** [comment]
@MartijnR - Do you know what scenarios aren't currently supported? Having the trigger as something in a repeating group?

I'd like to know what to expect to not work for now so we can focus on other tests.

**Comment by MartijnR** [comment]
Anything that produces relative path values for `ref` attributes (such as `ref="../bp_dt_ymd"` instead of absolute paths. I'm guessing this only happens with certain setvalue directives inside repeats, but haven't been able to investigate yet.

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/1R5IDQRC2yqn0WakVmq6oHslnCKIDVe-NOufkKktLfZ0/edit?usp=sharing

**Comment by MartijnR** [comment]
https://github.com/XLSForm/pyxform/issues/477

**Comment by MartijnR** [comment]
likely fixed. Doublecheck with latest pyxform

**Comment by pbowen-oc** [comment]
@MartijnR - We are still getting the same errors in this case even with Pyxform 1.3.1:

Found setvalue for “bp_dt_ymd ” that does not exist in the model.
Found setvalue for “bp_dt_ym ” that does not exist in the model.
Found setvalue for “bp_dt_y ” that does not exist in the model.

**Comment by MartijnR** [comment]
I don't when using https://getodk.org/xlsform/ and https://validate.enketo.org/oc/. 

I do actually get another error though (only in OC mode):

```bash
Errors:

about:blank:1:3: disallowed character. 
```

**Comment by pbowen-oc** [comment]
@MartijnR - Thanks. We are reviewing our deployment as it looks like there was an issue with it.

**Comment by pbowen-oc** [comment]
Looks good in testing.
