### ISSUE TITLE
Item name missing in error message

### ISSUE THREAD

**Issue by pbowen-oc** [enketo/enketo-validate#88]
The attached form is invalid since it is has instance('clinicaldata') calculation logic for an item but does not have bind::oc:external = clinicaldata. There is an error message for this, but it is missing the name of the item (listed as "null"):

Found calculation for question "null" that refers to external clinicaldata without the required "external" attribute in the correct namespace. 

[Form 7 version 1.zip](https://github.com/enketo/enketo-validate/files/5405756/Form.7.version.1.zip)

**Comment by MartijnR** [comment]
I think something went wrong during the update of enketo-validate. This was fixed already.

**Comment by pbowen-oc** [comment]
Looks good in testing
