### ISSUE TITLE
No validation error if set value trigger refers to calculate item that has a label defined mistakenly

### ISSUE THREAD

**Issue by pbowen-oc** [enketo/enketo-validate#89]
I think this is an issue with https://github.com/XLSForm/pyxform/issues/452, but putting it here to verify first.

If a calculate type item has a label defined (which generally has no effect since there is nowhere to display the label) and another item references that calculate item as a set value trigger, the set value calculation is silently ignored during form conversion.

Example:
[Default Trigger version 1f.zip](https://github.com/enketo/enketo-validate/files/5587542/Default.Trigger.version.1f.zip)
[trigger test 1f.xml.txt](https://github.com/enketo/enketo-validate/files/5587541/trigger.test.1f.xml.txt)

**Comment by MartijnR** [comment]
Questions serving as triggers have to have a form control: https://xlsform.org/en/#trigger

It sounds like that is the issue. The pyxform issue is about warning the user that this won't work.

**Comment by pbowen-oc** [comment]
@MartijnR - It seems like the Pyxform logic for determining if an item has a form control is incorrectly handling some non-form control calculate items. I was expecting the same user error text in this case so the user would know their trigger was not included in the XForm.

Can you log a Pyxform issue for this?

**Comment by MartijnR** [comment]
https://github.com/XLSForm/pyxform/issues/486

**Comment by pbowen-oc** [comment]
Looks good in testing.
