### ISSUE TITLE
Validate rejecting items with hint but no label

### ISSUE THREAD

**Issue by pbowen-oc** [enketo/enketo-validate#93]
Upload a form containing a text item with a hint but no label. Pyxform passes it, but Validate rejects it with an error:
Question ItemX has no label.

Based on a related Pyxform issue - https://github.com/XLSForm/pyxform/issues/451#issuecomment-659444768 - I expected this item to be permitted.

**Comment by MartijnR** [comment]
https://docs.google.com/spreadsheets/d/1ytvpQWensdHzoh19JHNKu8YNvXq4aQ3uNwGc9P4jzT0/edit?usp=sharing

**Comment by MartijnR** [comment]
This behavior is by design: https://github.com/XLSForm/pyxform/issues/439. 

Let me check if we can disable it temporarily until the above pyxform issue is implemented.

**Comment by MartijnR** [comment]
tolerance added in 1.12.2

**Comment by pbowen-oc** [comment]
Looks good in testing.
